import 'package:flutter/material.dart';

import 'model/tweet.dart';
import 'model/user.dart';

class App extends ChangeNotifier {
  User user = User(username: 'sarf01k', displayName: 'isaac sarfo', profileImageURL: 'assets/images/pfp.jpg', followersCount: 54, followingCount: 201);

  var tweets = [
    Tweet(
      avatar: 'https://pbs.twimg.com/profile_images/1187814172307800064/MhnwJbxw_400x400.jpg',
      username: 'Flutter',
      displayName: 'FlutterDev',
      timeAgo: '5m',
      text: 'Google’s UI toolkit to build apps for mobile, web, & desktop from a single codebase.',
      comments: '243',
      retweets: '23K',
      likes: '112K',
    ),
    Tweet(
      avatar: 'https://pbs.twimg.com/profile_images/1364344779685904387/1_8LtlJ2_400x400.jpg',
      username: 'pr_alphaa',
      displayName: 'ALPHA🥷🏻',
      timeAgo: '57m',
      text: 'Fastest weekend I\'ve seen ngl',
      comments: '2',
      retweets: '1',
      likes: '6',
    ),
    Tweet(
      avatar: 'https://pbs.twimg.com/profile_images/994592419705274369/RLplF55e_400x400.jpg',
      username: 'MrBeast',
      displayName: 'Mr. Beast',
      timeAgo: '36m',
      text: 'I just got measured at 6’5. Why am I still getting taller in my 20s 😭',
      comments: '1.5K',
      retweets: '21K',
      likes: '633K',
    ),
    Tweet(
      avatar: 'https://pbs.twimg.com/profile_images/1699794612284706816/TSeEIXud_400x400.jpg',
      username: 'CozyBrian_',
      displayName: 'Brian Joestar',
      timeAgo: '1h',
      text: 'Okay, look, I\'m honest\nGirl, i can\'t lie, I miss you',
      comments: '0',
      retweets: '0',
      likes: '8',
    ),
    Tweet(
      avatar: 'https://pbs.twimg.com/profile_images/1704985558571732992/mXW6pnbI_400x400.jpg',
      username: 'hoesmadfbg',
      displayName: 'Selah',
      timeAgo: '2m',
      text: 'every company in this country is so unserious. telcos, ecg, ghana water, fire service, police, everybody. ah',
      comments: '1',
      retweets: '1',
      likes: '3',
    ),
    Tweet(
      avatar: 'https://pbs.twimg.com/profile_images/1620474361336438800/bkZoDziE_400x400.jpg',
      username: 'meetwinnerr',
      displayName: 'Winner',
      timeAgo: '6m',
      text: 'Currently using GetX',
      comments: '0',
      retweets: '0',
      likes: '2',
    ),
    Tweet(
      avatar: 'https://pbs.twimg.com/profile_images/1628772053175177217/EGVJXNqO_400x400.jpg',
      username: 'manifestive',
      displayName: 'M.anifest',
      timeAgo: '4h1h',
      text: 'Thousand times in a row I excel in every column',
      comments: '12',
      retweets: '4',
      likes: '23K',
    ),
    Tweet(
      avatar: 'https://pbs.twimg.com/profile_images/1647987489439637509/ED9VLsDQ_400x400.jpg',
      username: 'ck_aboagye',
      displayName: 'CK',
      timeAgo: '6m',
      text: '우리의 희생이 헛되지 않기를 바랍니다',
      comments: '0',
      retweets: '1',
      likes: '2',
    ),
    Tweet(
      avatar: 'https://pbs.twimg.com/profile_images/1691458182005346304/3wd43r2y_400x400.jpg',
      username: 'Billyblxnco',
      displayName: 'Billyblxnco',
      timeAgo: '21h',
      text: 'switching off the bathroom light while your sibling is inside >>>',
      comments: '20',
      retweets: '7',
      likes: '893',
    ),
    Tweet(
      avatar: 'https://pbs.twimg.com/profile_images/728198940630384640/-NQMf0qy_400x400.jpg',
      username: 'THePunnyWorld',
      displayName: 'PUNS',
      timeAgo: '40m',
      text: 'My wife has banned me from making anymore breakfast puns.\n\nShe says if I make anymore, I’m toast.\n\nBut my kids keep egging me on.',
      comments: '56',
      retweets: '41',
      likes: '201K',
    ),
    Tweet(
      avatar: 'https://pbs.twimg.com/profile_images/1711813252965961728/yoQzC17h_400x400.jpg',
      username: '0x7fff5fbff7c8',
      displayName: 'aglili👨🏻‍💻👨🏻‍🍳',
      timeAgo: '26m',
      text: 'since i completed this school i’ve been sooo free bro',
      comments: '5',
      retweets: '2',
      likes: '11',
    )
  ];
}